threadnum: 3
durtion: 1800
concurrentuser: 3
ramptime: 1
casefolder: projectpath\testfolder\testcase
resultrootfolder: projectpath\testfolder\testresult
batfolder: projectpath\testfolder\batfolder


################邮件配置##################
mail:
pwd:
mailto:
mailcopy:
mailtitle: 性能测试报告
mail_encoding: utf8
mailtxt:
mailnick: LeePerfTest